#+TITLE: Linear Algebra Part 1

Because Linear Algebra really doesn't need several semesters. It's syntax.

* Vectors
On a real number line, we can describe any point by a single number. In more
than one dimension, to describe a point, we need more than a single number. In
2D space ($\mathbb{R}^2$), we conventionally denote points by their $x$ and $y$
coordinates.
\[ (x, y) \in \mathbb{R}^2
\]

In three dimensions, we'd have three coordinates, and in higher dimensional
space we'd need even more. (We actually mean a vector space: see
[[Vector Spaces]]).

We can define vectors as a tuple (fixed collection) of numbers, or in other
forms. The following is /column vector/ <<column vector>> form.
\[\begin{bmatrix} x_1 \\ \vdots \\ x_n \end{bmatrix} \in \mathbb{R}^n
\]

There is also row vector form, which is much the same, except horizontally.

** TODO Vector Operations
We can perform operations on these points, like adding them together, which
is pretty much what you expect.
\[(x_1, y_1) + (x_2, y_2) = (x_1 + x_2, y_1 + y_2) \in \mathbb{R}^2
\]
Subtraction is quite similar.

There are a few slightly more interesting operations on vectors we can
define. For example, what is the product of two multidimensional numbers? Does
it make sense to multiply $(3, 9)$ by $2$? What about $(1, 2) \times (3, 4, 5)$?

The first case seems reasonable. If we move north 5m and east 2m, then we can
indeed think of 'doubling' the distance we've just travelled, by moving north
10m and east 4m.
\[2 \times \begin{bmatrix} 5 \\ 2 \end{bmatrix} = \begin{bmatrix} 10 \\ 4 \end{bmatrix}
\]

Multiplying a vector by a vector is not the same, though. Multiplying the
individual components of one vector by another has proven to not be very useful
in practice, and mathematicians and physicists have come up with other, more
useful operations.

The most common one we will run into is the /vector dot product/, which is the
sum of the product of every component of a vector:
\[\begin{bmatrix} 1 \\ 3 \end{bmatrix} . \begin{bmatrix} 2 \\ 0 \end{bmatrix}
  = 1 \times 2 + 3 \times 0 = 2
\]

This takes two vectors in the same space and returns a real number. For
applications of the dot product, we have ??????????????????????????????????

There is also the cross product, but I'm not sure if there are any useful
applications of that in what we'll be studying.

* TODO Vector Spaces

* TODO Matrices
